version: '3'
services:
  auth:
    image: "kryptonorg/krypton-auth"
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: "mongodb://mongo:27017/users"
  mongo:
    image: "mongo"
